### ISSUE TITLE
Unable to find module in 2.1.6

### ISSUE THREAD

**Issue by dfalling** [anisjonischkeit/bs-marky-markdown#6]
I'm unable to use the latest release.

```bash
> bsb -make-world
...
The module or file MarkyMarkdown can't be found.
```

I realize I need to use `.make` instead of `.marky`, but BuckleScript can't find the module.  Any other changes I need to make?

bucklescript: 5.2.1

Thanks!

**Comment by anisjonischkeit** [comment]
Try it again with 2.1.7. accidentally added `namespace: true` to my bsconfig.

**Comment by dfalling** [comment]
That got it!  Thanks!
